# Generated by Django 3.2.6 on 2021-09-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerManage', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='CustomerManage.Tag'),
        ),
    ]
