# Generated by Django 3.2.6 on 2021-10-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerManage', '0009_auto_20211004_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/CustomerManage/Images/default-profile-picture.png', null=True, upload_to=''),
        ),
    ]
